name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test -- --coverage
    
    # Optional: Upload coverage to Codecov
    # Uncomment when you've set up Codecov integration
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     directory: ./coverage/
    #     fail_ci_if_error: true
    #     verbose: true
        
    # Save coverage report as an artifact
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage/
